# Generated by Django 6.0.6 on 2026-06-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
